import { describe, expect, it } from 'vitest';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { compile } from '../src/compile.js';
import { defaultFormatWriters } from '../src/formats/index.js';
import type { BinArtifact } from '../src/formats/types.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

describe('PR125 ISA: CB rotate/shift full matrix', () => {
  it('encodes rlc/rrc/rl/rr/sla/sra/srl for all reg8 + (hl)', async () => {
    const entry = join(__dirname, 'fixtures', 'pr125_cb_rotate_matrix.zax');
    const res = await compile(entry, {}, { formats: defaultFormatWriters });
    expect(res.diagnostics).toEqual([]);

    const bin = res.artifacts.find((a): a is BinArtifact => a.kind === 'bin');
    expect(bin).toBeDefined();
    expect(bin!.bytes).toEqual(
      Uint8Array.of(
        0xcb,
        0x00,
        0xcb,
        0x01,
        0xcb,
        0x02,
        0xcb,
        0x03,
        0xcb,
        0x04,
        0xcb,
        0x05,
        0xcb,
        0x06,
        0xcb,
        0x07,
        0xcb,
        0x08,
        0xcb,
        0x09,
        0xcb,
        0x0a,
        0xcb,
        0x0b,
        0xcb,
        0x0c,
        0xcb,
        0x0d,
        0xcb,
        0x0e,
        0xcb,
        0x0f,
        0xcb,
        0x10,
        0xcb,
        0x11,
        0xcb,
        0x12,
        0xcb,
        0x13,
        0xcb,
        0x14,
        0xcb,
        0x15,
        0xcb,
        0x16,
        0xcb,
        0x17,
        0xcb,
        0x18,
        0xcb,
        0x19,
        0xcb,
        0x1a,
        0xcb,
        0x1b,
        0xcb,
        0x1c,
        0xcb,
        0x1d,
        0xcb,
        0x1e,
        0xcb,
        0x1f,
        0xcb,
        0x20,
        0xcb,
        0x21,
        0xcb,
        0x22,
        0xcb,
        0x23,
        0xcb,
        0x24,
        0xcb,
        0x25,
        0xcb,
        0x26,
        0xcb,
        0x27,
        0xcb,
        0x28,
        0xcb,
        0x29,
        0xcb,
        0x2a,
        0xcb,
        0x2b,
        0xcb,
        0x2c,
        0xcb,
        0x2d,
        0xcb,
        0x2e,
        0xcb,
        0x2f,
        0xcb,
        0x38,
        0xcb,
        0x39,
        0xcb,
        0x3a,
        0xcb,
        0x3b,
        0xcb,
        0x3c,
        0xcb,
        0x3d,
        0xcb,
        0x3e,
        0xcb,
        0x3f,
        0xc9,
      ),
    );
  });
});
